# Generated by Django 3.2.5 on 2021-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20211007_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED'), ('WORKING', 'WORKING'), ('IN MAINTENANCE', 'IN MAINTENANCE')], default='NEW', max_length=20),
        ),
    ]
