# Generated by Django 4.0.6 on 2023-10-12 09:35

from django.db import migrations, models
import ecomstore.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('heartwoodbeyond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclaimed_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_publish', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ecomstore.catalog.models.RichTextField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now_add=True, editable=False)),
            ],
            options={
                'db_table': 'reclaimed_blog',
            },
        ),
    ]
