# Generated by Django 4.0.6 on 2022-10-27 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecomstore.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heartwoodbeyond', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads_Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=' ', max_length=100, null=True)),
                ('last_name', models.CharField(default=' ', max_length=100, null=True)),
                ('middle_name', models.CharField(default=' ', max_length=100, null=True)),
                ('company_name', models.CharField(default=' ', max_length=100, null=True)),
                ('executive_title', models.CharField(default=' ', max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('employees_size', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', ecomstore.catalog.models.RichTextField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now_add=True, editable=False)),
            ],
            options={
                'db_table': 'heartwood_leadspurchased',
            },
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='notes',
            field=ecomstore.catalog.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='open_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT4ADMIN', 'Wait for Administrator'), ('WAIT4CUSTOMER', 'Wait for Customer')], default='WAIT4ADMIN', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('is_current_customer', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('business_type', models.CharField(blank=True, max_length=30, null=True)),
                ('business_name', models.CharField(blank=True, max_length=30, null=True)),
                ('sign_up_for_newsletter', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('device', models.CharField(default='Desktop', max_length=20)),
                ('last_updated', models.DateField(auto_now_add=True, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'heartwood_customerrelationship',
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('subject', models.CharField(default='No subject', max_length=40)),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Customer Message')),
                ('admin_contact_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Our Response')),
                ('customer_attachment_1', models.FileField(blank=True, upload_to='customercontact/')),
                ('customer_attachment_2', models.FileField(blank=True, upload_to='customercontact/')),
                ('our_attachment_1', models.FileField(blank=True, upload_to='customercontact/')),
                ('our_attachment_2', models.FileField(blank=True, upload_to='customercontact/')),
                ('has_response_been_sent', models.BooleanField(default=False, verbose_name='Our response sent?')),
                ('contact_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartwoodbeyond.customerrelationship')),
            ],
            options={
                'db_table': 'heartwood_correspondence',
            },
        ),
    ]
