# Generated by Django 4.0.6 on 2022-10-03 20:06

from django.db import migrations, models
import django.db.models.deletion
import ecomstore.catalog.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='AmazonOrderReturnAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.CharField(blank=True, max_length=30, null=True)),
                ('order_id', models.CharField(max_length=30)),
                ('sku', models.CharField(max_length=30)),
                ('asin', models.CharField(max_length=30)),
                ('fnsku', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('fulfillment_center_id', models.CharField(max_length=30)),
                ('detailed_disposition', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('lpn', models.CharField(max_length=30)),
                ('customer_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('internal_status', models.CharField(choices=[('NOT RECEIVED', 'NOT RECEIVED'), ('RECEIVED, READY TO CHECK', 'RECEIVED, READY TO CHECK'), ('NEW CONDITION', 'NEW CONDITION'), ('DAMAGED RETURN', 'DAMAGED RETURN'), ('FRAUD RETURN', 'FRAUD RETURN'), ('REPORTED', 'REPORTED'), ('REJECTED', 'REJECTED'), ('RESOVLED', 'RESOLVED')], default='NOT RECEIVED', max_length=50)),
                ('internal_comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'amazonorderreturnaudit',
            },
        ),
        migrations.CreateModel(
            name='AmazonOrderReturnAuditImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_image', stdimage.models.StdImageField(upload_to='images/AmazonOrderReturnAudit/main')),
                ('image_caption', models.CharField(blank=True, max_length=200, null=True)),
                ('AmazonOrderReturnAudit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMA.amazonorderreturnaudit')),
            ],
            options={
                'db_table': 'AmazonOrderReturnAuditImages',
            },
        ),
    ]
