# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=200)),
                ('credit_card_number', models.CharField(max_length=16)),
                ('credit_card_security', models.CharField(max_length=10)),
                ('credit_card_expiration', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['customer_name'],
                'db_table': 'customer_accounts',
            },
        ),
        migrations.CreateModel(
            name='CustomerOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('offer_price', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerAccounts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
