# Generated by Django 3.2.5 on 2021-10-10 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heartwoodflooring_finishinggrade',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('heartwood_content', models.CharField(max_length=50)),
                ('grain_pattern', models.CharField(max_length=50)),
                ('grain_orientation', models.CharField(choices=[('VERTICAL', 'VERTICAL GRAIN'), ('HORIZONTAL', 'HORIZONTAL GRAIN')], default='VERTICAL', max_length=50)),
                ('density', models.CharField(max_length=50)),
                ('knots', models.CharField(max_length=50)),
                ('nail_holes', models.CharField(max_length=50)),
                ('widths', models.CharField(max_length=50)),
                ('lengths', models.CharField(max_length=50)),
                ('thicknesss', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'heartwoodflooring_finishingpattern',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heartwoodflooring_finishingtype',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('yield_estimate', models.DecimalField(decimal_places=2, default=0.5, max_digits=9)),
                ('purchase_date', models.DateField(blank=True, help_text='For an old asset, provide an estimate', null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='total', max_digits=9)),
                ('purchase_quantity', models.IntegerField(default=1)),
                ('vendor', models.CharField(blank=True, help_text='This asset was initially purchased from', max_length=100, null=True)),
                ('vendor_url', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_email', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('finishing_grade', models.ForeignKey(help_text='Natural Grade, Blue Stainn Grade, etc', on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.finishinggrade')),
                ('finishing_pattern', models.ForeignKey(blank=True, help_text='Quartersawn, Select, Natural, etc', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.finishingpattern')),
                ('finishing_type', models.ForeignKey(help_text='raw material, prefinished, etc', on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.finishingtype')),
            ],
            options={
                'db_table': 'heartwoodflooring_products',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heartwoodflooring_usagetype',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_of_measurement', models.CharField(choices=[('BF', 'Board Foot'), ('SF', 'Square Foot')], default='SF', max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='usage_type',
            field=models.ForeignKey(help_text='Beam, decking, joist, etc', on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.usagetype'),
        ),
    ]
