# Generated by Django 3.2.5 on 2021-10-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventorymanagement.product'),
        ),
    ]
