# Generated by Django 3.2.5 on 2021-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0002_auto_20211010_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
