# Generated by Django 3.2.5 on 2021-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0003_alter_product_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
