# Generated by Django 3.2.5 on 2021-10-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0004_product_item_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
