# Generated by Django 3.2.5 on 2021-10-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0005_product_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_cost',
            field=models.CharField(default='USD $0.00', max_length=50),
        ),
    ]
