# Generated by Django 3.2.5 on 2021-10-12 18:31

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0006_alter_product_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='more_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='images/inventorymanagement/')),
                ('document', models.FileField(blank=True, upload_to='inventorymanagement/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanagement.product')),
            ],
        ),
    ]
