# Generated by Django 3.2.5 on 2021-10-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0007_auto_20211012_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='more_details',
            new_name='more_detail',
        ),
    ]
