# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2021-05-19 13:10
from __future__ import unicode_literals


from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('url_link', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('image', stdimage.models.StdImageField(upload_to=b'images/misc/')),
                ('created_at', models.DateField(auto_now=True, editable=False)),
            ],
            options={
                'db_table': 'misc_todaysnews',
            },
        ),
    ]
